import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import { Box, Container } from '@mui/material';
import HeaderTabs from '@/components/HeaderTabs';
import CurrentPath from '@/components/CurrentPath';
import { Suspense } from 'react';
import ModalRoot from '@/components/modals/ModalRoot';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body>
        <Providers>
          <Box
            sx={{
              display: 'grid',
              gridTemplateRows: 'auto 1fr',
              height: '100dvh',
            }}
          >
            <HeaderTabs />
            <Container
              id="main-content"
              component="main"
              sx={{ minHeight: 0, overflow: 'auto', display: 'grid', gridTemplateRows: 'auto 1fr', py: 1 }}
            >
              <CurrentPath />
              {children}
            </Container>
          </Box>
          <Suspense fallback={null}>
            <ModalRoot />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
